---
# tasks file for wordpress

# Download wordpress
# - name: Delete content & directory in public_html
#   file:
#     state: absent
#     path: /var/www/html/wordpress/public_html/

# - name: create fresh public_html for wordpress
#   file: 
#     path: /var/www/html/wordpress/public_html
#     state: directory
#     mode: 0775
#     recurse: yes

# - name: Download wordpress file
#   get_url:
#     url: https://wordpress.org/latest.tar.gz
#     dest: /var/www/html/wordpress/public_html/wordpress.tar.gz

# - name: Extract wordpress.tar.gz
#   unarchive:
#     remote_src: yes
#     src: /var/www/html/wordpress/public_html/wordpress.tar.gz
#     dest: /var/www/html/wordpress/public_html

# - name: Move wordpress contents to public_html
#   shell: sudo mv /var/www/html/wordpress/public_html/wordpress/* /var/www/html/wordpress/public_html

# - name: Remove wordpress folder
#   shell: sudo rm -rf wordpress


# Prerequisites
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
  tags: [wordpress]

- name: Install LAMP Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'apache2', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
  # Packer doesn't like mysql-server: "No package matching 'mysql-server' is available"
  # loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
  tags: [ wordpress ]

- name: Install PHP Extensions
  apt: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"
  tags: [ wordpress ]

# Apache Configuration
- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags: [ wordpress ]

- name: Set up Apache VirtualHost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: Reload Apache
  tags: [ wordpress ]

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache
  tags: [ wordpress ]

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache
  tags: [ wordpress ]

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: Restart Apache
  tags: [ wordpress ]

# UFW Configuration
# - name: "UFW - Allow HTTP on port {{ http_port }}"  # Note: packer fails here
#   ufw:
#     rule: allow
#     port: "{{ http_port }}"
#     proto: tcp

# PHP Info Page
- name: Sets Up PHP Info Page
  template:
    src: "files/info.php.j2"
    dest: "/var/www/{{ http_host }}/info.php"
  tags: [ wordpress ]

# WordPress Configuration

- name: Delete content & directory in public_html
  file:
    state: absent
    path: /var/www/wordpress
  tags: [ wordpress ]

- name: create fresh public_html for wordpress
  file: 
    path: /var/www/wordpress
    state: directory
    mode: 0775
    recurse: yes
  tags: [ wordpress ]

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"
  tags: [ wordpress ]

# - name: Set ownership
#   file:
#     path: "/var/www/{{ http_host }}"
#     state: directory
#     recurse: yes
#     owner: www-data
#     group: www-data
#   tags: [ wordpress ]

# - name: Set permissions for directories
#   shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
#   tags: [ wordpress ]

# - name: Set permissions for files
#   shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
#   tags: [ wordpress ]

- name: Move wordpress contents to public_html
  shell: sudo mv /var/www/wordpress/wordpress/* /var/www/wordpress/
  tags: [ wordpress ]

- name: Remove wordpress folder
  shell: sudo rm -rf /var/www/wordpress/wordpress
  tags: [ wordpress ]

- name: Change ownership
  shell: sudo chown -R $USER /var/www/
  tags: [ wordpress ]

- name: Set up wp-config
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wp-config.php"
  tags: [ wordpress ]