- name: Ensure apache is not installed
  apt:
    name: apache2
    state: absent
  tags: [http-server]

- name: Ensure nginx is present or install it
  apt:
    name: nginx
    state: present
    update_cache: true
  tags: [http-server]

- name: Replace nginx site config
  copy:
    src: site.conf
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx
  tags: [http-server]